# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [5]:
# Import your libraries:
from sklearn.datasets import load_diabetes
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function.

In [7]:
# Your code here:
diabetes = load_diabetes()

Let's explore this variable by looking at the different attributes. Do this by looking at the `keys()` of this variable.

In [9]:
# Your code here:
diabetes.keys()


dict_keys(['data', 'target', 'DESCR', 'feature_names', 'data_filename', 'target_filename'])

The next step is to read the description of the dataset. Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable

In [13]:
# Your code here:
print(diabetes.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - Age
      - Sex
      - Body mass index
      - Average blood pressure
      - S1
      - S2
      - S3
      - S4
      - S5
      - S6

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bra

What are the variables in this dataset according to the description? List them in the markdown cell below

#### Enter your answer here:




Now explore the data. Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). In the cell below find the shape of the numpy array contained in the data portion of the diabetes variable.

In [14]:
# Your code here:
diabetes.data.shape


(442, 10)

# Challenge 2 - Perform Supervised Learning on the Dataset

#### The data has already been split to predictor and response variables. The response variable is in the `target` portion of the variable. 

Given this information, let's apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset. In the cell below, import the linear regression class from sklearn. 

In [18]:
# Your code here:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

Initialize the model in the variable `diabetes_model`

In [19]:
# Your code here:

diabetes_model = LinearRegression()

In the cell below, fit the model and print the intercept and coefficients of the model. 

In [20]:
# Your code here:

X = diabetes.data
y = diabetes.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 9)

lin_reg = diabetes_model.fit(X_train, y_train)

y_pred = diabetes_model.predict(X_test)
r2_score(y_test, y_pred)

0.5851141269959739

In [21]:
#coeficientes
diabetes_model.coef_

array([  -18.86413017,  -267.9587748 ,   453.72923819,   352.56614997,
       -1016.98682421,   717.60317584,   153.69396101,   177.68903276,
         860.61296074,    50.80497338])

In [22]:
#intercept
diabetes_model.intercept_

153.071929832646

# Bonus Challenge 1 - Conduct a Hypothesis Test on the Model

Once we have generated a linear model, we can test each coefficient using a t-test to see whether the confidence interval for the variable contains zero. We can also perform an overall F test to check whether at least one coefficient is significantly different from zero. 

Refer to the resource in this [link](https://onlinecourses.science.psu.edu/stat501/node/297/) for more details and perform the t-tests for the model above. Additionally, interpret the results and list coefficients are significantly different from zero.


Hint: use the statsmodels package.

Your result should look similar to this:

![ols](../ols-results.png)

In [23]:
# Your code here:
import statsmodels.api as sm
from statsmodels.regression.linear_model import OLS

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [24]:
X = sm.add_constant(diabetes.data)
y = diabetes.target

In [25]:
linreg_stats = sm.OLS(y,X).fit()

In [26]:
print(linreg_stats.summary())
#r2 es muy lejano a 1, por lo que no es un buen modelo para predecir

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.106
Model:                            OLS   Adj. R-squared (uncentered):              0.085
Method:                 Least Squares   F-statistic:                              5.100
Date:                Tue, 16 Feb 2021   Prob (F-statistic):                    4.72e-07
Time:                        22:20:18   Log-Likelihood:                         -2873.9
No. Observations:                 442   AIC:                                      5768.
Df Residuals:                     432   BIC:                                      5809.
Df Model:                          10                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

# Challenge 2 - Peform Supervised Learning on a Pandas Dataframe

Now that we have looked at data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [29]:
# Your code here:
auto = pd.read_csv('/content/drive/MyDrive/1. IRONHACK/BBDD/Copia de auto-mpg.csv')

Look at the first 5 rows using the `head()` function:

In [30]:
# Your code here:
auto.head(5)


mpg  cylinders  ...  model_year                       car_name
0  18.0          8  ...          70  \t"chevrolet chevelle malibu"
1  15.0          8  ...          70          \t"buick skylark 320"
2  18.0          8  ...          70         \t"plymouth satellite"
3  16.0          8  ...          70              \t"amc rebel sst"
4  17.0          8  ...          70                \t"ford torino"

[5 rows x 8 columns]

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [31]:
# Your code here:

auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horse_power   392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   car_name      398 non-null    object 
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB


What is the newest model year and the oldest model year?

In [32]:
# Your code here:

print(f"Min: {auto.model_year.min()}")
print(f'Max: {auto.model_year.max()}')

Min: 70
Max: 82


Check the dataset for missing values and remove all rows containing at least one missing value.

In [34]:
# Your code here:
auto.isnull().sum()
#only horse_power has nulls

mpg             0
cylinders       0
displacement    0
horse_power     6
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

In [35]:
auto.dropna(axis=0, inplace = True)
auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horse_power     0
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [36]:
# Your code here:
auto.cylinders.value_counts()
#there are 5 possible values

4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

In [45]:
# Copy the dataset
auto_2 = auto.copy()

In [46]:
#drop the car_name column since it does not contain any quantitative data
auto_2.drop(columns=['car_name'], inplace=True)

In [47]:
auto_2.head()

mpg  cylinders  displacement  horse_power  weight  acceleration  model_year
0  18.0          8         307.0        130.0    3504          12.0          70
1  15.0          8         350.0        165.0    3693          11.5          70
2  18.0          8         318.0        150.0    3436          11.0          70
3  16.0          8         304.0        150.0    3433          12.0          70
4  17.0          8         302.0        140.0    3449          10.5          70

In [48]:
#separate the dataframe to predictor and response variables
X = auto_2.drop(columns=['mpg'])
y = auto_2.mpg

In [49]:
#Separate those into test and training data with 80% of the data in the training set and the remainder in the test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 9)

Now we will the dataset that we processed and peform linear regression on this data to predict the mpg for each vehicle. Initialize the model in the cell below.

In [50]:
# Your code here:
mpg_model = LinearRegression()

Next, fit the model in the cell below.

In [52]:
# Your code here:
mpg_model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# Challenge 3 - Evaluate the Model

the r squared score of a model tells us how much variation is explained by the model. In a typical dataset, most observations differ from the mean. When we create a model, we are trying to generate an equation that will tell us by how much each observation will differ from the mean. Obviously, the vast majority of models are not perfect. They can only predict some of the variation from the mean but not all of it. We attribute the rest of the difference between the actual value and the mean to random error. We would like random error to explain the as little as possible of the variation. This is why the r squared score is an important metric.

In the next cell, compute the r squared score of the model. Do this by first computing the predicted values and assign them to `y_pred`.

In [53]:
# Your code here:
y_pred = mpg_model.predict(X_test)
y_pred

array([19.0922132 , 25.90746445, 11.02073199, 15.16740593, 27.95946172,
       17.38512423, 19.97253054, 13.22628406, 19.32587017, 25.78012599,
       31.896663  , 23.74854968, 24.67138003, 20.5947445 , 21.2074667 ,
       16.80555834, 22.38709709, 32.00235699, 30.24531879, 21.71574456,
       14.668089  , 26.18462758, 20.25616607, 28.56329947, 26.4533103 ,
       23.11405964, 17.08966305, 23.00820733, 27.15539254, 34.29652027,
       11.56407966, 23.09736507, 19.40983092, 24.34053917, 31.74758138,
        9.00559217, 31.1447843 , 24.03810832, 30.2190343 , 20.97358721,
       34.72066989, 33.31705635, 25.29453399, 12.85190244, 27.65060855,
       16.1199124 , 28.3955319 , 32.30952964, 23.42290858, 29.9710625 ,
       23.29931244, 19.64990959, 33.71684659, 32.52265174, 23.94782274,
       17.61419969, 28.60212616, 11.93568855, 30.56068017, 14.72850495,
       13.64476119, 12.51232362, 21.80479061, 11.97454328, 21.84700666,
       31.5508896 , 29.89378259, 20.90115684, 31.34536345, 21.19

#### Our next step is to evaluate the model using the test data. We would like to ensure that our model is not overfitting the data. This means that our model will not be able to generalize well outside of the training data.

In the cell below, use the model to generate the predicted values for the training data and assign them to `y_test_pred`. Compute the r squared score for the test data by comparing the oberserved `y_test` data and the predicted `y_test_pred`.

In [54]:
# Your code here:
r2_score(y_test, y_pred)

0.8259555584834548

# Challenge 4 - Improve the Model Fit

While the most common way to improve the fit of a model is by using regularization, there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [55]:
# Your code here:
X_train09, X_test09, y_train09, y_test09 = train_test_split(X, y, test_size = 0.1, random_state=9)

Initialize a new model. Name this model `auto_model09`. Fit the model to the new sample data.

In [56]:
# Your code here:
auto_model09 = LinearRegression()

auto_model09.fit(X_train09, y_train09)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

Compute the predicted values and r squared score for our new model and new sample data.

In [58]:
# Your code here:

y_pred09 = auto_model09.predict(X_test09)
y_pred09

array([18.8778387 , 25.97340703, 10.88405991, 15.36060896, 27.72875615,
       17.23496542, 19.83210656, 13.32462087, 19.33405569, 25.97830782,
       31.86129078, 24.06261621, 24.83496644, 20.71367514, 21.50027004,
       17.11851789, 22.37609285, 32.16279524, 30.48558681, 22.14001912,
       14.87453365, 26.04631688, 20.20445624, 28.58301654, 26.25260394,
       23.25447779, 16.82994797, 22.7829202 , 26.85548981, 34.45694267,
       11.09192179, 23.25023347, 19.71910138, 24.34728247, 31.95404615,
        8.4120402 , 31.37316403, 24.23768943, 30.3783612 , 21.42980288])

Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [59]:
# Your code here:
r2_score(y_test09, y_pred09)

#decrecio mi score de 0.8259 a 0.8243

0.8242366806886212

# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

In [60]:
from sklearn.feature_selection import RFE

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [61]:
# Your code here:
auto_model = LinearRegression()
rfe_model = RFE(auto_model, n_features_to_select = 3)

Fit the model and print the ranking

In [62]:
# Your code here:

rfe_model.fit(X,y)
rfe_model.ranking_

array([1, 2, 4, 3, 1, 1])

Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [65]:
# Your code here:
X.head(1)

#array([1, 2, 4, 3, 1, 1]) = cylinders, acceleration, model_year

cylinders  displacement  horse_power  weight  acceleration  model_year
0          8         307.0        130.0    3504          12.0          70

In [66]:
X_ranked = ['cylinders','acceleration','model_year']

In [67]:
# Your code here:

X_train_reduced, X_test_reduced, y_train_reduced, y_test_reduced = train_test_split(X[X_ranked], y, test_size = 0.2, random_state=9)

Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [68]:
# Your code here: 

auto_model_reduced = LinearRegression().fit(X_train_reduced, y_train_reduced)

In [69]:
y_test_pred_reduced = auto_model_reduced.predict(X_test_reduced)
r2_score(y_test_reduced, y_test_pred_reduced)
#la r2 decreció, por lo que no ayudo el eliminar columnas 

0.6994356944511378